export interface Product {
  id: string
  name: string
  category: string
  subcategory: string
  image: string

  // ✅ renamed field
  fabric: string

  // ✅ BRA extra fields
  cupSize?: string
  sizeRange?: string
  variety?: number

  // ✅ Panty + Slips extra
  type?: string
  elasticType?: string
  colors?: number

  neck? : string
}

export const categories = [
  { id: "bra", name: "Bra" },
  { id: "panties", name: "Panties" },
  { id: "slips", name: "Slips" },
  { id: "sets", name: "Sets" },
]

export const categorySubcategories: Record<string, any[]> = {
  bra: [
    { id: "everyday", name: "Everyday Bra's" },
    { id: "cotton", name: "100% Cotton Bra's" },
    { id: "padded", name: "Padded Bra's" },
    { id: "sports", name: "Sport Bra's" },
    { id: "net", name: "Net / Bridal Bra's" },
    { id: "softpadded", name: "Soft padded Bra's" },
    { id: "feeding", name: "Feeding Bra's" },
  ],

  panties: [
    { id: "basic", name: "Basic Panties" },
    { id: "period", name: "Period Panties" },
    { id: "boyshorts", name: "Boy Shorts Panties" },
    { id: "supporter", name: "Supporter Panties" },
    { id: "modal", name: "Modal Fabric Panties" },
    { id: "smallElastic", name: "Small Elastic" },
    { id: "innerElastic", name: "Inner Elastic" },
  ],

  slips: [
    { id: "top", name: "Top Slip" },
    { id: "full", name: "Full Slip" },
    { id: "gown", name: "Gown Slip" },
  ],

  sets: [
    { id: "padded", name: "Padded Sets" },
    { id: "plain", name: "Plain Sets" },
    { id: "printed", name: "Printed Sets" },
    { id: "net", name: "Net / Bridal Sets" },
  ],
}

export const products: Product[] = [
  // =========================
  // ✅ BRA (FEEDING)
  // =========================
  {
    id: "bra-feeding-saachi",
    name: "Saachi",
    category: "bra",
    subcategory: "feeding",
    image: "/saachi-feeding.png",
    fabric: "Hosiery",
    cupSize: "B",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)",
    variety: 6,
  },
  {
    id: "bra-feeding-havells",
    name: "Havells",
    category: "bra",
    subcategory: "feeding",
    image: "/havells-feeding.png",
    fabric: "Hosiery",
    cupSize: "B",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)",
    variety: 6,
  },

  // =========================
  // ✅ BRA (EVERYDAY)
  // =========================
  {
    id: "bra-everyday-nike",
    name: "Nike",
    category: "bra",
    subcategory: "everyday",
    image: "/nike-everyday.png",
    fabric: "Hosiery",
    cupSize: "B",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)",
    variety: 6,
  },
  {
    id: "bra-everyday-nicky",
    name: "Nicky",
    category: "bra",
    subcategory: "everyday",
    image: "/nicky-everyday.png",
    fabric: "Hosiery",
    cupSize: "B",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)",
    variety: 3,
  },
  {
    id: "bra-everyday-sherry",
    name: "Sherry",
    category: "bra",
    subcategory: "everyday",
    image: "/sherry-everyday.png",
    fabric: "Cotton Lycra",
    cupSize: "B",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)",
    variety: 6,
  },
  // pic not in public folder and drive
  {
    id: "bra-everyday-labela",
    name: "Labela (C / D)",
    category: "bra",
    subcategory: "everyday",
    image: "/labela-everyday.jpeg",
    fabric: "Hosiery",
    cupSize: "C / D",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)",
    variety: 9,
  },
  
  {
    id: "bra-everyday-clovia",
    name: "Clovia (D)",
    category: "bra",
    subcategory: "everyday",
    image: "/clovia-everyday.png",
    fabric: "Cotton Lycra",
    cupSize: "D",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)",
    variety: 6,
  },
  {
    id: "bra-everyday-vista",
    name: "Vista (C/D)",
    category: "bra",
    subcategory: "everyday",
    image: "/vista-everyday.png",
    fabric: "Hosiery",
    cupSize: "C / D",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)",
    variety: 9,
  },
  {
    id: "bra-everyday-divya",
    name: "Divya (C)",
    category: "bra",
    subcategory: "everyday",
    image: "/divya-everyday.png",
    fabric: "Hosiery",
    cupSize: "C",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)",
    variety: 9,
  },
  //same photo as divya
  {
    id: "bra-everyday-nancy",
    name: "Nancy",
    category: "bra",
    subcategory: "everyday",
    image: "/divya-everyday.png",
    fabric: "Hosiery",
    cupSize: "B",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)",
    variety: 6,
  },
  {
    id: "bra-everyday-hazel",
    name: "Hazel (C)",
    category: "bra",
    subcategory: "everyday",
    image: "/hazel-everyday.png",
    fabric: "Cotton Lycra",
    cupSize: "C",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)",
    variety: 6,
  },
  
  {
    id: "bra-everyday-spykar",
    name: "Spykar (C) {Side Support}",
    category: "bra",
    subcategory: "everyday",
    image: "/spykar-everyday.png",
    fabric: "Hosiery",
    cupSize: "C",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)",
    variety: 6,
  },
  
  {
    id: "bra-everyday-nidhi",
    name: "Nidhi (C)",
    category: "bra",
    subcategory: "everyday",
    image: "/nidhi-everyday.png",
    fabric: "Hosiery",
    cupSize: "C",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)",
    variety: 6,
  },
  
  {
    id: "bra-everyday-altis",
    name: "Altis (D)",
    category: "bra",
    subcategory: "everyday",
    image: "/altis-everyday.png",
    fabric: "Hosiery",
    cupSize: "D",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)",
    variety: 9,
  },
  
  {
    id: "bra-everyday-neha",
    name: "Neha",
    category: "bra",
    subcategory: "everyday",
    image: "/neha-everyday.png",
    fabric: "Hosiery",
    cupSize: "B",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)",
    variety: 3,
  },
  {
    id: "bra-everyday-unique",
    name: "Unique",
    category: "bra",
    subcategory: "everyday",
    image: "/unique-everyday.png",
    fabric: "Hosiery",
    cupSize: "B",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)",
    variety: 6,
  },
  {
    id: "bra-everyday-sting",
    name: "Sting { Backless }",
    category: "bra",
    subcategory: "everyday",
    image: "/sting-everyday.jpeg",
    fabric: "Hosiery",
    cupSize: "B",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)",
    variety: 6,
  },
  {
    id: "bra-everyday-lovable",
    name: "Lovable",
    category: "bra",
    subcategory: "everyday",
    image: "/lovable-everyday.png",
    fabric: "Cotton Lycra",
    cupSize: "B",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)",
    variety: 6,
  },
  {
    id: "bra-everyday-sonali",
    name: "Sonali",
    category: "bra",
    subcategory: "everyday",
    image: "/sonali-everyday.png",
    fabric: "Hosiery",
    cupSize: "B",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)",
    variety: 6,
  },
  {
    id: "bra-everyday-twist",
    name: "Twist {Mould}",
    category: "bra",
    subcategory: "everyday",
    image: "/twist-everyday.jpeg",
    fabric: "Hosiery",
    cupSize: "B",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)",
    variety: 6,
  },

  // =========================
  // ✅ 100% COTTON BRAS
  // =========================
  // same as swift everyday
  {
    id: "bra-cotton-swift",
    name: "Swift (C)",
    category: "bra",
    subcategory: "cotton",
    image: "/swift-everyday.jpeg",
    fabric: "100% Cotton",
    cupSize: "C",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)" ,
    variety: 3,
  },
   {
    id: "bra-cotton-kirti",
    name: "Kirti (D)",
    category: "bra",
    subcategory: "cotton",
    image: "/kirti-everyday.png",
    fabric: "100% Cotton",
    cupSize: "D",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)",
    variety: 3,
  },
  {
    id: "bra-cotton-wonder",
    name: "Wonder (C)",
    category: "bra",
    subcategory: "cotton",
    image: "/wonder-everyday.png",
    fabric: "100% Cotton",
    cupSize: "C",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)" ,
    variety: 3,
  },
  {
    id: "bra-cotton-extreme",
    name: "Extreme (C)",
    category: "bra",
    subcategory: "cotton",
    image: "/extreme-everyday.png",
    fabric: "100% Cotton",
    cupSize: "C",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)" ,
    variety: 3,
  },
  {
    id: "bra-cotton-roshni",
    name: "Roshni (D)",
    category: "bra",
    subcategory: "cotton",
    image: "/roshni-everyday.jpeg",
    fabric: "100% Cotton",
    cupSize: "D",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)",
    variety: 3,
  },
  {
    id: "bra-cotton-sakshi",
    name: "Sakshi (D)",
    category: "bra",
    subcategory: "cotton",
    image: "/sakshi-everyday.png",
    fabric: "100% Cotton",
    cupSize: "D",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)" ,
    variety: 3,
  },


  // =========================
  // ✅ NET / BRIDAL BRAS
  // =========================
  //no photo found for bra-net-vintage
  {
    id: "bra-net-vintage",
    name: "Vintage (C)",
    category: "bra",
    subcategory: "net",
    image: "/vintage-net.jpeg",
    fabric: "Lycra Net",
    cupSize: "C",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)" ,
    variety: 6,
  },
  {
    id: "bra-net-gemini",
    name: "Gemini (C)",
    category: "bra",
    subcategory: "net",
    image: "/gemini-net.jpeg",
    fabric: "Lycra Net",
    cupSize: "C",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)",
    variety: 6,
  },
  {
    id: "bra-net-trendy",
    name: "Trendy",
    category: "bra",
    subcategory: "net",
    image: "/trendy-net.png",
    fabric: "Lycra Net",
    cupSize: "B",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)" ,
    variety: 6,
  },
  {
    id: "bra-net-virtus",
    name: "Virtus (C)",
    category: "bra",
    subcategory: "net",
    image: "/virtus-net.jpeg",
    fabric: "Lycra Net",
    cupSize: "C",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)" ,
    variety: 6,
  },
  {
    id: "bra-net-gipsy",
    name: "Gipsy",
    category: "bra",
    subcategory: "net",
    image: "/gipsy-net.png",
    fabric: "Lycra Net",
    cupSize: "B",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)" ,
    variety: 6,
  },
  // =========================
  // ✅ PADDED BRAS
  // =========================
  // no photo found for bra-padded-glory
  {

    id: "bra-padded-glory",
    name: "Glory",
    category: "bra",
    subcategory: "padded",
    image: "/glory-padded.jpeg",
    fabric: "Hosiery",
    cupSize: "B",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)" ,
    variety: 15,
  },
  {
    id: "bra-padded-bela",
    name: "Bela ",
    category: "bra",
    subcategory: "padded",
    image: "/bela-padded.png",
    fabric: "Cotton Lycra",
    cupSize: "B",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)" ,
    variety: 3,
  },
  {
    id: "bra-padded-tipsy",
    name: "Tipsy",
    category: "bra",
    subcategory: "padded",
    image: "/tipsy-padded.png",
    fabric: "Cotton Lycra",
    cupSize: "B",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)" ,
    variety: 6,
  },
  {
    id: "bra-padded-sinq",
    name: "Sinq",
    category: "bra",
    subcategory: "padded",
    image: "/sinq-padded.png",
    fabric: "Lycra",
    cupSize: "B",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)" ,
    variety: 6,
  },
  {
    id: "bra-padded-pushup",
    name: "Pushup",
    category: "bra",
    subcategory: "padded",
    image: "/pushup-padded.jpeg",
    fabric: "Cotton Lycra",
    cupSize: "B",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)" ,
    variety: 3,
  },
  {
    id: "bra-padded-chikpad",
    name: "Chik Pad { Backless }",
    category: "bra",
    subcategory: "padded",
    image: "/chikpad-padded.jpeg",
    fabric: "Lycra",
    cupSize: "B",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)" ,
    variety: 6,
  },
  {
    id: "bra-padded-nivea",
    name: "Nivea",
    category: "bra",
    subcategory: "padded",
    image: "/nivea-padded.png",
    fabric: "Cotton Lycra",
    cupSize: "B",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)" ,
    variety: 6,
  },

  // =========================
  // ✅ SOFT PADDED BRAS
  // =========================
  {
    id: "bra-soft-passion",
    name: "Passion (C)",
    category: "bra",
    subcategory: "softpadded",
    image: "/passion-softpadded.png",
    fabric: "Hosiery",
    cupSize: "C",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)",
    variety: 6,
  },
  // no photo found for bra-soft-syska
  {
    id: "bra-soft-syska",
    name: "Syska",
    category: "bra",
    subcategory: "softpadded",
    image: "/syska-softpadded.jpeg",
    fabric: "Hosiery",
    cupSize: "B",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)" ,
    variety: 8,
  },
  // no photo found for bra-soft-clavis
  {
    id: "bra-soft-clavis",
    name: "Clavis (D)",
    category: "bra",
    subcategory: "softpadded",
    image: "/clavis-softpadded.jpeg",
    fabric: "Hosiery",
    cupSize: "D",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)" ,
    variety: 3,
  },
  {
    id: "bra-soft-dazzle",
    name: "Dazzle (C)",
    category: "bra",
    subcategory: "softpadded",
    image: "/dazzle-softpadded.jpg",
    fabric: "Hosiery",
    cupSize: "C",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)" ,
    variety: 6,
  },
  {
    id: "bra-soft-carens",
    name: "Carens (C)",
    category: "bra",
    subcategory: "softpadded",
    image: "/carens-softpadded.jpeg",
    fabric: "Hosiery",
    cupSize: "C",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)" ,
    variety: 3,
  },

  // =========================
  // ✅ SPORTS BRAS
  // =========================
  {
    id: "bra-sports-zareen",
    name: "Zareen",
    category: "bra",
    subcategory: "sports",
    image: "/zareen-sports.png",
    fabric: "Cotton Lycra",
    cupSize: "B",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)" ,
    variety: 3,
  },
  {
    id: "bra-sports-tissot",
    name: "Tissot",
    category: "bra",
    subcategory: "sports",
    image: "/tissot-sports.png",
    fabric: "Hosiery",
    cupSize: "B",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)" ,
    variety: 6,
  },
  {
    id: "bra-sports-fiero",
    name: "Fiero",
    category: "bra",
    subcategory: "sports",
    image: "/fiero-sports.png",
    fabric: "Hosiery",
    cupSize: "B",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)" ,
    variety: 6,
  },
  {
    id: "bra-sports-activ",
    name: "Activ",
    category: "bra",
    subcategory: "sports",
    image: "/activ-sports.jpeg",
    fabric: "Cotton Lycra",
    cupSize: "B",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)" ,
    variety: 6,
  },
  {
    id: "bra-sports-daisy",
    name: "Daisy",
    category: "bra",
    subcategory: "sports",
    image: "/daisy-sports.png",
    fabric: "Hosiery",
    cupSize: "B",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)" ,
    variety: 6,
  },
  {
    id: "bra-sports-saloni",
    name: "Saloni",
    category: "bra",
    subcategory: "sports",
    image: "/saloni-sports.png",
    fabric: "Hosiery",
    cupSize: "B",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)" ,
    variety: 3,
  },
  {
    id: "bra-sports-image",
    name: "Image ",
    category: "bra",
    subcategory: "sports",
    image: "/image-sports.jpeg",
    fabric: "Cotton Lycra",
    cupSize: "B",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)" ,
    variety: 6,
  },

  // =========================
  // ✅ SETS PRODUCTS
  // =========================
  {
    id: "set-padded-jolly",
    name: "Jolly",
    category: "sets",
    subcategory: "padded",
    image: "/jolly-padded-set.png",
    fabric: "Hosiery",
    cupSize: "B",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)" ,
    colors: 6,
  },
  {
    id: "set-padded-avni",
    name: "Avni",
    category: "sets",
    subcategory: "padded",
    image: "/avni-padded-set.png",
    fabric: "Lycra",
    cupSize: "B",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)" ,
    colors: 3,
  },
  {
    id: "set-padded-zoya",
    name: "Zoya",
    category: "sets",
    subcategory: "padded",
    image: "/zoya-padded-set.png",
    fabric: "Lycra Net",
    cupSize: "B",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)" ,
    colors: 6,
  },

  {
    id: "set-plain-crazy",
    name: "Crazy",
    category: "sets",
    subcategory: "plain",
    image: "/crazy-plain-set.png",
    fabric: "Hosiery",
    cupSize: "B",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)" ,
    colors: 6,
  },

  {
    id: "set-printed-myra",
    name: "Myra",
    category: "sets",
    subcategory: "printed",
    image: "/myra-printed-set.png",
    fabric: "Hosiery",
    cupSize: "B",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)" ,
    colors: 3,
  },
  {
    id: "set-printed-mahek",
    name: "Mahek",
    category: "sets",
    subcategory: "printed",
    image: "/mahek-printed-set.png",
    fabric: "Hosiery",
    cupSize: "B",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)" ,
    colors: 3,
  },

  {
    id: "set-net-gypsy",
    name: "Gypsy",
    category: "sets",
    subcategory: "net",
    image: "/gypsy-net-set.png",
    fabric: "Lycra Net",
    cupSize: "B",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)" ,
    colors: 6,
  },
  {
    id: "set-net-trendy",
    name: "Trendy",
    category: "sets",
    subcategory: "net",
    image: "/trendy-net-set.png",
    fabric: "Lycra Net",
    cupSize: "B",
    sizeRange: "30-44 (Size range may vary from product to product and is subject to availability)" ,
    colors: 6,
  },

  // =========================
  // ✅ SLIPS PRODUCTS
  // =========================
  
  {
    id: "slip-top-gouri",
    name: "Gouri",
    category: "slips",
    subcategory: "top",
    image: "/gouri-top-slip.jpeg",
    fabric: "Hosiery",
    type: "Top Slip",
    colors: 3,
    neck: "U Neck"
  },
  {
    id: "slip-top-kashish",
    name: "Kashish",
    category: "slips",
    subcategory: "top",
    image: "/kashish-top-slip.jpeg",
    fabric: "Hosiery",
    type: "Top Slip",
    colors: 3,
    neck: "V Neck"
  },
  {
    id: "slip-top-neva",
    name: "Neva",
    category: "slips",
    subcategory: "top",
    image: "/neva-top-slip.jpeg",
    fabric: "Ribbed Cotton",
    type: "Top Slip",
    colors: 3,
    neck: "U Neck"
  },
  {
    id: "slip-top-dolphin",
    name: "Dolphin",
    category: "slips",
    subcategory: "top",
    image: "/dolphin-top-slip.jpeg",
    fabric: "Cotton Lycra",
    type: "Top Slip",
    colors: 3,
    neck:"Plain"
  },
  {
    id: "slip-top-comfy",
    name: "Comfy",
    category: "slips",
    subcategory: "top",
    image: "/comfy-top-slip.jpeg",
    fabric: "Ribbed Lycra",
    type: "Top Slip",
    colors: 3,
    neck: "Round Neck"
  },

  {
    id: "slip-full-heena",
    name: "Heena",
    category: "slips",
    subcategory: "full",
    image: "/heena-full-slip.jpeg",
    fabric: "Hosiery",
    type: "Full Slip",
    colors: 3,
    neck: "Round Neck"
  },

  {
    id: "slip-gown-sonam",
    name: "Sonam",
    category: "slips",
    subcategory: "gown",
    image: "/sonam-gown-slip.png",
    fabric: "Hosiery",
    type: "Gown Slip",
    colors: 15,
    neck: "Round Neck"
  },

  // =========================
  // ✅ PANTIES PRODUCTS
  // =========================

  {
    id: "panty-suppoerter-anny",
    name: "Anny (75 mm)",
    category: "panties",
    subcategory: "supporter",
    image: "/anny-supporter-panty.png",
    fabric: "Cotton",
    type: "Supporter Panty",
    elasticType: "Inner elastic",
    colors: 3,
  },
  {
    id: "panty-suppoerter-max",
    name: "Max (75 mm)",
    category: "panties",
    subcategory: "supporter",
    image: "/max-supporter-panty.png",
    fabric: "Cotton",
    type: "Supporter Panty",
    elasticType: "Outer elastic",
    colors: 3,
    //outer elastic 
  },
  {
    id: "panty-suppoerter-vanilla",
    name: "Vanilla (75 mm)",
    category: "panties",
    subcategory: "supporter",
    image: "/vanilla-supporter-panty.png",
    fabric: "Cotton",
    type: "Supporter Panty",
    elasticType: "Outer elastic",
    colors: 3,
  },
  {
    id: "panty-period-comfortx",
    name: "ComfortX {Period Panty}",
    category: "panties",
    subcategory: "period",
    image: "/comfortx-period-panty.png",
    fabric: "Cotton Lycra",
    type: "Period Panty",
    elasticType: "Inner elastic",
    colors: 6,
  },

  {
    id: "panty-boy-sonal",
    name: "Sonal (Print)",
    category: "panties",
    subcategory: "boyshorts",
    image: "/sonal-boyshorts-panty.png",
    fabric: "Viscose Lycra",
    type: "Boy Shorts",
    elasticType: "Inner elastic",
    colors: 3,
  },
  {
    id: "panty-boy-brio",
    name: "Brio ",
    category: "panties",
    subcategory: "boyshorts",
    image: "/brio-boyshorts-panty.png",
    fabric: "Modal Lycra",
    type: "Boy Shorts",
    elasticType: "Inner elastic",
    colors: 6,
  },
  {
    id: "panty-boy-hify",
    name: "Hi-Fy",
    category: "panties",
    subcategory: "boyshorts",
    image: "/hify-boyshorts-panty.jpeg",
    fabric: "Cotton Lycra",
    type: "Boy Shorts",
    elasticType: "Small Outer elastic",
    colors: 6,
  },

  {
    id: "panty-basic-jazz",
    name: "Jazz {CSP}",
    category: "panties",
    subcategory: "basic",
    image: "/jazz-basic-panty.png",
    fabric: "Hosiery",
    type: "Basic Panty",
    elasticType: "Outer Broad elastic",
    colors: 6,
  },
  {
    id: "panty-basic-sonnet",
    name: "Sonnet",
    category: "panties",
    subcategory: "basic",
    image: "/sonnet-basic-panty.png",
    fabric: "Cotton",
    type: "Basic Panty",
    elasticType: "Small Outer elastic",
    colors: 3,
  },
  {
    id: "panty-basic-safire",
    name: "Safire {CSP}",
    category: "panties",
    subcategory: "basic",
    image: "/safire-basic-panty.png",
    fabric: "Hosiery Stripe",
    type: "Basic Panty",
    elasticType: "Outer broad elastic",
    colors: 3,
  },
  {
    id: "panty-basic-della",
    name: "Della",
    category: "panties",
    subcategory: "basic",
    image: "/della-basic-panty.jpeg",
    fabric: "Cotton",
    type: "Basic Panty",
    elasticType: "Outer broad elastic",
    colors: 3,
  },
  {
    id: "panty-basic-allday",
    name: "All Day",
    category: "panties",
    subcategory: "basic",
    image: "/basic-allday-panty.png",
    fabric: "Cotton Lycra",
    type: "Modal Panty",
    elasticType: "Outer small elastic",
    colors: 6,
    
  },

  {
    id: "panty-modal-print",
    name: "Modal Print",
    category: "panties",
    subcategory: "modal",
    image: "/modal-print-panty.png",
    fabric: "Modal Lycra",
    type: "Modal Panty",
    elasticType: "Semi inner elastic",
    colors: 3,
  },
  // {
  //   id: "panty-modal-brio",
  //   name: "Brio ",
  //   category: "panties",
  //   subcategory: "modal",
  //   image: "/modal-brio-panty.png",
  //   fabric: "Modal Lycra",
  //   type: "Modal Panty",
  //   elasticType: "soft elastic",
  //   colors: 6,
  // },
  
  {
    id: "panty-modal-softy",
    name: "Softy",
    category: "panties",
    subcategory: "modal",
    image: "/modal-softy-panty.png",
    fabric: "Modal Lycra",
    type: "Modal Panty",
    elasticType: "Semi inner elastic",
    colors: 6,
  },
  //cant find info
  // {
  //   id: "panty-small-derby",
  //   name: "Derby",
  //   category: "panties",
  //   subcategory: "smallElastic",
  //   image: "/placeholder.svg",
  //   fabric: "cotton plain",
  //   type: "Small Elastic Panty",
  //   elasticType: "small elastic",
  //   colors: ["white", "black"],
  // },
  {
    id: "panty-small-soha",
    name: "Soha",
    category: "panties",
    subcategory: "smallElastic",
    image: "/soha-small-elastic-panty.png",
    fabric: "Hosiery",
    type: "Small Elastic Panty",
    elasticType: "small outer ",
    colors: 3,
  },
  {
    id: "panty-small-feeling",
    name: "Feelings",
    category: "panties",
    subcategory: "smallElastic",
    image: "/feelings-small-elastic-panty.png",
    fabric: "Cotton",
    type: "Small Elastic Panty",
    elasticType: "small Outer",
    colors: 6,
  },

  {
    id: "panty-inner-seema",
    name: "Seema",
    category: "panties",
    subcategory: "innerElastic",
    image: "/seema-inner-elastic-panty.jpeg",
    fabric: "Cotton",
    type: "Inner Elastic Panty",
    elasticType: "inner elastic",
    colors: 6,
  },
  {
    id: "panty-inner-anny",
    name: "Anny (75 mm)",
    category: "panties",
    subcategory: "innerElastic",
    image: "/anny-supporter-panty.png",
    fabric: "Cotton",
    type: "Inner Elastic Panty",
    elasticType: "inner elastic",
    colors: 3,
  },
  {
    id: "panty-inner-elina",
    name: "Elina ",
    category: "panties",
    subcategory: "innerElastic",
    image: "/elina-inner-elastic-panty.png",
    fabric: "Hosiery",
    type: "Inner Elastic Panty",
    elasticType: "inner elastic",
    colors: 3,
  },
  {
    id: "panty-inner-nidhi",
    name: "Nidhi ",
    category: "panties",
    subcategory: "innerElastic",
    image: "/nidhi-inner-elastic-panty.jpeg",
    fabric: "Cotton",
    type: "Inner Elastic Panty",
    elasticType: "inner elastic",
    colors: 3,
  },
  {
    id: "panty-inner-cool",
    name: "Cool",
    category: "panties",
    subcategory: "innerElastic",
    image: "/cool-inner-elastic-panty.png",
    fabric: "Viscose Lycra",
    type: "Inner Elastic Panty",
    elasticType: "inner elastic",
    colors: 3,
  },
]
